export const NAVEEN = {
  name: "M. Naveen",
  role: "Aspiring Data Engineer",
  subtitle: "AI & Data Science Engineer",
  email: "naveen.ai25@stellamaryscoe.edu.in",
  phone: "+91 6381412882",
  location: "Erode, Tamil Nadu",
  portfolio: "naveen-portfolio-ebon.vercel.app",
  linkedin: "linkedin.com/in/naveen-m",
  github: "github.com/nrnnaveen",
  college: "Stella Mary's College of Engineering",
  degree: "B.Tech Artificial Intelligence & Data Science",
  period: "2025 – 2029",
  cgpa: "8.5",
  objective:
    "Aspiring Data Engineer with expertise in Python and SQL, seeking to contribute to a reputed IT organization by building scalable data systems and delivering impactful data-driven solutions.",
  skills: [
    "Python","PostgreSQL","MySQL","SQL","IoT",
    "HTML5","Web Designing","Data Analysis","Git",
    "MS Word","MS Excel","MS PowerPoint",
  ],
  languages: ["Tamil","English","Telugu"],
  hobbies: ["Explore New Tech","Coding Small Projects","Cooking"],
  projects: [
    { name:"SQL Mobile Playground", desc:"An interactive mobile application that allows users to write, execute, and experiment with SQL queries in a hands-on environment.", tech:["SQL","Mobile","UI/UX"], color:"#00fff7" },
    { name:"All Cutoff Calculator",  desc:"A utility tool designed to calculate academic cutoff scores across various Tamil Nadu entrance systems with precision and ease.", tech:["Python","Math","Education"], color:"#bf00ff" },
    { name:"Frequency Analysis App", desc:"An application for performing statistical frequency analysis on datasets, aiding in pattern recognition and data interpretation.", tech:["Python","Statistics","Data Analysis"], color:"#00ff88" },
    { name:"Gen AI",                  desc:"An exploratory project integrating Generative AI capabilities to produce intelligent, context-aware responses and content.", tech:["AI","Python","GenAI"], color:"#ff6b35" },
    { name:"AI Voice Model (Offline)",desc:"A lightweight, offline-capable voice recognition model built to function without internet connectivity, enabling local AI inference.", tech:["AI","ML","Offline","Python"], color:"#00c8ff" },
    { name:"Guardian AI",             desc:"An intelligent AI-powered Students safety and monitoring solution designed to predict and Reduce Drop out Rates In College/University, providing real-time alerts and protective functionalities.", tech:["AI","Safety","ML","IoT"], color:"#ff0080" },
  ],
  achievements: [
    "Active Member of Orator's Club",
    "Basher @Byte-Bash-Blitz",
    "Participated In Data Refinery Contest (D.I.A)",
    "Participated In IIC Hack & NimirnthuNil Hack",
    "Participated In AI Expo & Hackathon 2k25",
  ],
  education: [
    { label:"B.Tech AI & Data Science", place:"Stella Mary's College of Engineering", year:"2025–2029", score:"8.5 CGPA" },
    { label:"HSC",  place:"GHSS, Vellankovil", year:"2025", score:"80%" },
    { label:"SSLC", place:"GHSS, Vellankovil", year:"2023", score:"83%" },
  ],
} as const
